services:
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres

  whatsapp:
    extends:
      file: docker-compose.base.yml
      service: whatsapp
    environment:
      - WHATSAPP_WEBHOOK=http://web-server:8000/webhook
      - APP_BASIC_AUTH=${WHATSAPP_BASIC_AUTH_USER}:${WHATSAPP_BASIC_AUTH_PASSWORD}

  web-server:
    build:
      context: .
      args:
        INSTALL_LOCAL: "false"
    volumes:
      - ./src:/app/src
      - ./migrations:/app/migrations
      - F:/wa_llm_data/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - whatsapp
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - PORT=8000
      - DB_URI=postgresql+asyncpg://user:password@postgres:5432/webhook_db
      - WHATSAPP_HOST=http://whatsapp:3000

volumes:
  wa_llm_whatsapp:
    name: wa_llm_whatsapp
  wa_llm_postgres:
    name: wa_llm_postgres